version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-push:
    executor:
      name: node/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "6e:81:a8:bf:14:70:cf:b6:e9:95:b8:ec:08:70:cc:ad"
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Check versions
                command: |
                  node -v
                  yarn -v
            - run:
                name: Install packages
                command: yarn install
            - run:
                name: Create build with webpack
                command: yarn run build
            - run:
                name: Check generated files
                command: ls -all
            - run:
            - run:
                name: Copy dist repo
                command:


workflows:
    build-and-push:
      jobs:
        - build-and-push