version: 2.1
orbs:
  node: circleci/node@2.0.2
jobs:
  build-and-push:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: node -v
            - run: yarn -v
workflows:
    build-and-test:
      jobs:
        - build-and-test